validate.py: "one" tag check (in tandem with neaten.py)
amir-zeldes/gum pull request #126
Opened 2022-10-22 15:03 UTC by nschneid

cf. UniversalDependencies/UD_English-EWT@3182a98

2022-10-24 18:29 UTC, amir-zeldes requested changes

2022-10-24 18:35 UTC, nschneid commented on _build/utils/validate.py
> +			      ("no","DT","one","CD")]
Ah, that case doesn't come up in EWT.

2022-10-24 18:36 UTC, amir-zeldes commented on _build/utils/validate.py
> +			      ("no","DT","one","CD")]
OK, but I think it's also not needed given that you have the check above. If you remove this one I'll merge it for GUM as well.

2022-10-24 18:42 UTC, nschneid commented on _build/utils/validate.py
> +			      ("no","DT","one","CD")]
The point was that it should be no/DT one/NN

2022-10-24 19:08 UTC, amir-zeldes commented on _build/utils/validate.py
> +			      ("no","DT","one","CD")]
Right, but not in "no/DT one/CD group" - there it's a regular numerical one, and the DT is attaching to "group". The first check should still work and will not flag this case incorrectly, right?

2022-10-24 19:29 UTC, nschneid commented on _build/utils/validate.py
> +			      ("no","DT","one","CD")]
Oh I see it now. Yes. "no one" is a special case of det(one/NN, *). So lines 948 & 949 are unnecessary.

2022-10-24 19:42 UTC, amir-zeldes commented on _build/utils/validate.py
> +			      ("no","DT","one","CD")]
Great, if you revise the PR I'll merge this.

2022-10-25 00:03 UTC, nschneid commented
Done. You may also want to run neaten.py on the generated GUM .conllus; it now checks a bunch of features etc.

2022-10-25 14:06 UTC, amir-zeldes commented
Ideally we should integrate it into the GUM buildbot, but I see there is now a lot of redundancy between the buildbot and neaten... Something to look into in the future I guess.

2022-10-25 14:08 UTC, merged